#!/bin/bash

if command -v zig &>/dev/null; then
  ZIG_VERSION="$(zig version | awk -F. '{OFS="."; $NF=0; print}')"
  #cd /tmp
  wget https://github.com/zigtools/zls/releases/download/$ZIG_VERSION/zls-$(uname -m)-linux.tar.xz
  [ -d /tmp/zls ] && rm -rf /tmp/zls
  mkdir /tmp/zls
  tar -C /tmp/zls -xf ./zls-$(uname -m)-linux.tar.xz
  sudo install /tmp/zls/zls /usr/local/bin
  # cleanup
  [ -d /tmp/zls ] && rm -rf /tmp/zls
  [ -f ./zls-$(uname -m)-linux.tar.xz ] && rm -rf ./zls-$(uname -m)-linux.tar.xz
  cd -
else
  echo "Please install zig first"
fi
