#!/bin/bash

#display and exit-on-error for all commands
set -e
set +v

echo "Installing golang"

GO_VERSION=""
FORCE=""

usage()
{

cat << eof
usage: install_go.sh <options>
-v, --version      go version to install (Optional: if not provided latest version is installed)
-h, --help         get usage info
eof
}

while [ "$1" != "" ]; do
    PARAM=`echo $1 | awk -F= '{print $1}'`
    VALUE=`echo $1 | awk -F= '{print $2}'`
    case $PARAM in
        -v | --version )
            GO_VERSION=go$(echo $VALUE | tr -d '"')
        ;;
        -f | --force )
            FORCE="Y"
        ;;
        -h | --help )
            usage
            exit
    esac
    shift
done

if [[ -z "$GO_VERSION" ]]; then
    GO_VERSION="$(curl -s -L https://golang.org/VERSION?m=text | head -n 1)"
fi

if [[ -z "$FORCE" ]]; then
    if command -v go &> /dev/null
    then
        CURR_VERSION="$(go version | cut -d ' ' -f 3)"
        [[ "$CURR_VERSION" == "$GO_VERSION" ]] && { echo "$GO_VERSION already installed !!"; exit 0; }
        echo "Current Version: $CURR_VERSION"
    fi
fi

pushd /tmp
echo "Downloading go version $GO_VERSION"
wget https://golang.org/dl/$GO_VERSION.linux-amd64.tar.gz
[ -d /usr/local/go ] && sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf $GO_VERSION.linux-amd64.tar.gz

popd
