#!/bin/bash


if command -v zig &> /dev/null
then
    ZIG_VERSION="$(zig version)"
    cd /tmp
    wget https://github.com/zigtools/zls/releases/download/$ZIG_VERSION/zls-$(uname -m)-linux.tar.gz
    [ -d /tmp/zls ] && rm -rf /tmp/zls
    mkdir /tmp/zls
    tar -C /tmp/zls -xzf ./zls-$(uname -m)-linux.tar.gz
    sudo install /tmp/zls/bin/zls /usr/local/bin
    cd -
else
    echo "Please install zig first"
fi

# x